### ISSUE TITLE
Things to fix before public launch

### ISSUE THREAD

**Issue by dankohn** [LFDLFoundation/landscape#15]
- [x] Add LFDL Landscape and LFDL logo at bottom center of landscape. Remove Redpoint and Amplify logos
- [x] I don't think referencing Kube-batch makes sense, since it's just a core feature of Kubernetes. I would suggest replacing with this Kubernetes content https://github.com/cncf/landscape/blob/master/landscape.yml#L991-L999
- [x] Please create a separate Google Analytics sub-account for https://landscape.deeplearningfoundation.org
- [x] Add Sitemap
- [x] Update Favicon to LFDL Landscape version

**Comment by ZeusTheTrueGod** [comment]
Google analytics makes sense when we decide what is the final site url.

**Comment by ZeusTheTrueGod** [comment]
I'd also add an updated sitemap, then setup an update server and decide if we can work with a crunchbase. Lets add a cncf-bot to this repo so that bot can update our repo.

**Comment by dankohn** [comment]
We can continue to use the same CNCF key to work with Crunchbase.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ibrahimhaddad** [comment]
Replaced kube-batch with kubernetes per Dan's suggestion.

**Comment by ZeusTheTrueGod** [comment]
@alexcontini please send me a new favicon. Or updated it directly in the repo, 
https://github.com/LFDLFoundation/landscape/blob/master/src/favicon.png

**Comment by ibrahimhaddad** [comment]
I will start updating the README.md this coming week.
